introduce `save_to_db` in the calculator.py
zincware/MDSuite pull request #330
Opened 2021-09-20 10:42 UTC by PythonFZ

Make the calculators easier.

- Introduce common `save_to_db` method
- Store calculator arguments in the database and load results if already run
- updated all active tests / classes

# How to Test
Running this code multiple times should only trigger the computation once.
To force another computation you can use `experiment.version += 1`
```py
result = project.run.RadialDistributionFunction()
print(result.data_dict)
```

# TODO
- ~~check that adding additional data does force a rerun~~ 69d757d
- ~~provide an argument to return all computations if data has been added (return list instead of latest)~~ not fixed
- ~~output of load, run and run with arguments that are already computed should be the same -> plot + return data_dict~~
- update all disabled classes / tests
- fix Coordination Numbers
- ~~hange species, molecules to json dumps~~
- ~~Change computation data to json dumps~~
- ~~fix RDF, ADF only having a single species~~

2021-09-21 14:27 UTC, SamTov requested changes
I think the branch needs to be updated with the current dev but i will take care of this now. Otherwise there are some comments that should be addressed.

2021-09-21 14:27 UTC, SamTov commented on mdsuite/calculators/calculator.py
> +        self.species = None  # all species
Why is this now all species?

2021-09-21 14:27 UTC, SamTov commented on mdsuite/calculators/calculator.py
> +        self.species = None  # all species
Okay so if I understand correctly the selected species is the species currently being operated on by the calculator so that the database is updated correctly. Can this be renamed or the comments improved. Under one scope selected species is all of the species in the experiment that will be operated on and under another is a subset of those species currently being operated on.

2021-09-21 14:27 UTC, SamTov commented on mdsuite/calculators/structure_factor.py
>  plt.rcParams['figure.facecolor'] = 'white'
Has this been merged with the latest dev version? I think some of the parameter arguments and these params things are from an old dev version as I addressed a few in the visualization module.

2021-09-21 14:27 UTC, SamTov commented on mdsuite/database/calculator_database.py
>  class CalculatorDatabase:
doc strings here

2021-09-21 14:27 UTC, SamTov commented on mdsuite/database/experiment_database.py
can you fix the doc string for species

2021-09-21 14:27 UTC, SamTov commented on mdsuite/database/experiment_database.py
>      def radial_distribution_function_state(self) -> bool:
returns should also be in the doc strings

2021-09-21 14:27 UTC, SamTov commented on mdsuite/database/scheme.py
> +class ComputationSpecies(Base):
Should have a short doc string.

2021-09-21 14:27 UTC, SamTov commented on mdsuite/experiment/add_files.py
>                                    n_atoms=self.number_of_atoms,
the init of this class needs a doc string

2021-09-21 14:29 UTC, PythonFZ commented on mdsuite/calculators/structure_factor.py
>  plt.rcParams['figure.facecolor'] = 'white'
I just merged it. Had to manually make some changes

2021-09-21 14:36 UTC, PythonFZ commented on mdsuite/experiment/add_files.py
>                                    n_atoms=self.number_of_atoms,
fixed in 04edb32

2021-09-21 14:36 UTC, PythonFZ commented on mdsuite/database/scheme.py
> +class ComputationSpecies(Base):
fixed in 04edb32

2021-09-21 14:36 UTC, PythonFZ commented on mdsuite/database/calculator_database.py
>  class CalculatorDatabase:
fixed in 04edb32

2021-09-21 14:37 UTC, PythonFZ commented on mdsuite/calculators/calculator.py
> +        self.species = None  # all species
propably fixed in 04edb32 ?

2021-09-21 14:39 UTC, PythonFZ commented on mdsuite/database/experiment_database.py
>      def radial_distribution_function_state(self) -> bool:
The `@read_files.setter` does not have any return value. Did you mean another method or is this more a general comment?

2021-09-21 14:50 UTC, SamTov approved these changes
Looks better with the merged dev

2021-09-21 14:50 UTC, SamTov commented on mdsuite/calculators/calculator.py
>  import matplotlib.pyplot as plt
I don't think there is any mpl left.... at least there shouldnt be.

2021-09-21 14:50 UTC, SamTov commented on mdsuite/calculators/calculator.py
> +        self.species = None  # all species
Was this explanation correct though?

2021-09-21 14:51 UTC, SamTov commented on mdsuite/database/experiment_database.py
>      def radial_distribution_function_state(self) -> bool:
The rdf state method. Sorry I couldn't comment the exact line in the review.

2021-09-21 20:09 UTC, PythonFZ commented on mdsuite/calculators/calculator.py
> +        self.species = None  # all species
Yeah, it was. Species: all species to be investigated, selected_species: the current selection in this iteration, e.g. Li-Li or Li-Cl

2021-09-22 07:13 UTC, SamTov approved these changes
everything looks great.

2021-09-27 06:43 UTC, SamTov approved these changes
Changes look good. Glad the molecule loading is introduced.

2021-09-27 14:25 UTC, SamTov approved these changes
Looks good. A little hard to check everything but the functionality and general implementation works well.

2021-09-27 14:25 UTC, merged