Remove SDF Code
zincware/MDSuite pull request #467
Opened 2022-01-18 10:06 UTC by PythonFZ

Fix Issues with open3D e.g. in binder

- ZnVIS and open3D were either commented out or removed from the MDSuite code.

2022-01-19 11:08 UTC, SamTov requested changes
Just some comments about commenting things out rather than removing them.

2022-01-19 11:08 UTC, SamTov commented on mdsuite/calculators/__init__.py
> -    @property
I would prefer these are just commented out. They will return soon.

2022-01-19 11:08 UTC, SamTov commented on mdsuite/experiment/experiment.py
> -    def run_visualization(
Same as above

2022-01-19 11:08 UTC, SamTov commented on mdsuite/experiment/run.py
> -    @property
Same as above

2022-01-19 11:17 UTC, PythonFZ commented on mdsuite/calculators/__init__.py
> -    @property
Good point

2022-01-19 11:22 UTC, PythonFZ commented on mdsuite/experiment/run.py
> -    @property
resolved in fc233f4

2022-01-19 11:22 UTC, PythonFZ commented on mdsuite/experiment/experiment.py
> -    def run_visualization(
resolved in fc233f4

2022-01-19 11:23 UTC, PythonFZ commented on mdsuite/calculators/__init__.py
> -    @property
resolved in fc233f4

2022-01-21 13:43 UTC, SamTov approved these changes
Looks good.

2022-01-21 13:51 UTC, merged