set pubchempy defaults to false
zincware/MDSuite pull request #553
Opened 2022-08-10 16:46 UTC by SamTov

Fix #527 

I am, just setting the default to False in the code here so that it will not come up in the tests. This will at least improve dev speed for the time being until we can decide on next steps. It can still be turned on during data loading, however, the only thing loaded at the moment is mass. I would suggest we leave it like this until the db move is over and then think of how to have a more immersive experience in terms of populating particle properties.

#### Summary of additions and changes

* Set pubchempy call default to False

2022-08-12 07:19 UTC, PythonFZ commented
I don't know how to review the changes. I think we will come back to the PR when we found a solution for the tests.

2022-08-12 07:37 UTC, SamTov commented
> I don't know how to review the changes. I think we will come back to the PR when we found a solution for the tests.

Changes wise it's just setting pubchempy to false. Test fail due to masses not being present, They can be set in the tests I just haven't had the time to do it.

2023-01-26 16:20 UTC, christophlohrmann requested changes

2023-01-26 16:20 UTC, christophlohrmann commented on examples/notebooks/NaCl_walkthrough.ipynb
> +      "2023-01-22 21:54:00,097 - INFO: Creating new project NaCl_Example\n"
restart and clear all output

2023-01-27 08:50 UTC, christophlohrmann approved these changes

2023-01-27 08:50 UTC, merged